// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDt9pFnTRK_vnbbnxHc80Kv79SN62o3MmQ',
    appId: '1:1051682694104:web:d1274e5abbc0dff213c8ad',
    messagingSenderId: '1051682694104',
    projectId: 'whatsapp-34bcf',
    authDomain: 'whatsapp-34bcf.firebaseapp.com',
    storageBucket: 'whatsapp-34bcf.firebasestorage.app',
    measurementId: 'G-DQNDRKCR1J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCJuBAhTOeYl7j4U5uWN4TrsVd4PXgDnY',
    appId: '1:1051682694104:android:32e839abdcaf970113c8ad',
    messagingSenderId: '1051682694104',
    projectId: 'whatsapp-34bcf',
    storageBucket: 'whatsapp-34bcf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBU0v3JPbJVuVXbJLB5qMPfqfQ2S0xGA3U',
    appId: '1:1051682694104:ios:6396e78a87992f3613c8ad',
    messagingSenderId: '1051682694104',
    projectId: 'whatsapp-34bcf',
    storageBucket: 'whatsapp-34bcf.firebasestorage.app',
    iosBundleId: 'com.example.whatsappClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBU0v3JPbJVuVXbJLB5qMPfqfQ2S0xGA3U',
    appId: '1:1051682694104:ios:6396e78a87992f3613c8ad',
    messagingSenderId: '1051682694104',
    projectId: 'whatsapp-34bcf',
    storageBucket: 'whatsapp-34bcf.firebasestorage.app',
    iosBundleId: 'com.example.whatsappClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDt9pFnTRK_vnbbnxHc80Kv79SN62o3MmQ',
    appId: '1:1051682694104:web:ecb7c0f7ddbe4a2d13c8ad',
    messagingSenderId: '1051682694104',
    projectId: 'whatsapp-34bcf',
    authDomain: 'whatsapp-34bcf.firebaseapp.com',
    storageBucket: 'whatsapp-34bcf.firebasestorage.app',
    measurementId: 'G-XF1V0TCQ53',
  );
}
